import type { WireCategory, WireRecordType } from '../../types';

/** Unicode icon for each wire type. Chosen for distinguishability in a dense list. */
export const TYPE_ICON: Record<WireRecordType, string> = {
  metadata: '§',
  session_initialized: '✧',
  turn_begin: '▶',
  turn_end: '◼',
  user_message: '▷',
  tool_result: '✓',
  compaction: '⏪',
  system_prompt_changed: '¶',
  tools_changed: '⚙',
  system_reminder: '!',
  notification: '◉',
  // Streaming atoms: step boundary, streamed part, tool call
  step_begin: '┌',
  step_end: '┘',
  content_part: '◆',
  tool_call: '→',
  tool_denied: '⊘',
  skill_invoked: '★',
  skill_completed: '★',
  approval_request: '?',
  approval_response: '·',
  team_mail: '✉',
  subagent_spawned: '┬',
  subagent_completed: '└',
  subagent_failed: '×',
  ownership_changed: '↔',
  context_edit: '✂',
  context_cleared: '∅',
};

/** Tone key used by <Pill/>. Most types fall back to their category color. */
export const TYPE_TONE: Record<
  WireRecordType,
  WireCategory | 'user' | 'assistant' | 'tool' | 'compaction' | 'turn'
> = {
  metadata: 'meta',
  session_initialized: 'config',
  turn_begin: 'turn',
  turn_end: 'turn',
  user_message: 'user',
  tool_result: 'tool',
  compaction: 'compaction',
  system_prompt_changed: 'config',
  tools_changed: 'config',
  system_reminder: 'ephemeral',
  notification: 'meta',
  step_begin: 'turn',
  step_end: 'turn',
  content_part: 'assistant',
  tool_call: 'tools',
  tool_denied: 'approval',
  skill_invoked: 'tools',
  skill_completed: 'tools',
  approval_request: 'approval',
  approval_response: 'approval',
  team_mail: 'meta',
  subagent_spawned: 'subagent',
  subagent_completed: 'subagent',
  subagent_failed: 'subagent',
  ownership_changed: 'lifecycle',
  context_edit: 'lifecycle',
  context_cleared: 'lifecycle',
};
